server:
  port: 8081

spring:
  # 만약 active: mysql이 작동안하면(주석이면) h2 메모리 DB 사용됨
  # profiles:
  #   active: mysql

  # 기본 데이터소스 설정 (H2 인메모리 DB)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost:8081/kakao_login
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - profile_image
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  secret: "THIS_IS_TEST_JWT_SECRET_!CHANGE_ME!"
  expiration-ms: 3600000


kakao:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dnd_db
    username: dnd
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect