#name: Deploy To EC2
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  Deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Github Repository에 올린 파일들을 불러오기
##       아래는 파일불러오는 라이브러리(레파지토리에 저장된 코드를 불러옴)
#        uses: actions/checkout@v4
#
#      - name: JDK 21버전 설치
##        아래는 jdk 쉽게 설치해주는 라이브러리
#        uses: actions/setup-java@v4
#        with:
#          distribution: corretto
#          java-version: 21
#
#      - name: application.yml 파일 만들기
#        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml
#
#      - name: 테스트 및 빌드하기
#        run: ./gradlew clean build
#
#      - name: 빌드된 파일 이름 변경하기
#        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar
#
##        아래는 빌드된 파일을 EC2에 보냄
#      - name: SCP로 EC2에 빌드된 파일 전송하기
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          source: project.jar
##          아래는 EC2에 저장경로 지정하는 코드, 바뀔 프로젝트는 toBe 폴더에 넣어놓기
#          target: /home/ubuntu/dnd-12th-3-backend/tobe
#
#      - name: SSH(원격 접속)로 EC2에 접속하기
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script_stop: true
#          script: |
#            rm -rf /home/ubuntu/dnd-12th-3-backend/current
#            mkdir /home/ubuntu/dnd-12th-3-backend/current
#            mv /home/ubuntu/dnd-12th-3-backend/tobe/project.jar /home/ubuntu/dnd-12th-3-backend/current/project.jar
#            cd /home/ubuntu/dnd-12th-3-backend/current
#            sudo fuser -k -n tcp 8080 || true
#            nohup java -jar project.jar > ./output.log 2>&1 &
#            rm -rf /home/ubuntu/dnd-12th-3-backend/tobe
#
#
#
